### ISSUE TITLE
Switch to PMTiles

### ISSUE THREAD

**Issue by mem48** [nptscot/web#15]
With the launch of PMTiles v3 supporting compression, the main barrier to adoption has been removed.

Tests indicate a v3 `.pmtiles` file is now 6% smaller than a folder of gzipped `.pbf` files. Not a great saving, but significantly better than v2 which did not easily support compression and so was much larger. This also impacted performance.

The benefits of a single file vs a folder of millions of tiny files are huge. 

1. Easier file upload and version control
2. Possibility to switch to cloud hosting e.g. GCP as API billing based on per file uploaded not per MB uploaded.
3. Easier to incorporate into workflows

**Comment by mem48** [comment]
Support for pmtiles added and rnet already using them. Will update other layers as and when needed.

**Comment by Robinlovelace** [comment]
So cool Great work @mem48 !

**Comment by Robinlovelace** [comment]
And heads-up @bdon, your tech is being used to serve data supporting sustainable transport planning in Scotland (and maybe soon beyond)!

**Comment by bdon** [comment]
@Robinlovelace @mem48 nice work!
