### ISSUE TITLE
Thinking about legends

### ISSUE THREAD

**Issue by mem48** [nptscot/web#16]
The current website uses the PBCC approach. Of a floating box in the bottom left corner.

![image](https://user-images.githubusercontent.com/15819577/220074926-609ca139-3795-4b6f-8f70-4ad4e41c8bf1.png)

This can change contextually based on the rnet

![image](https://user-images.githubusercontent.com/15819577/220075194-ce38bd7b-2c34-4969-b090-53b4015590de.png)

And can be minimised for small screens

![image](https://user-images.githubusercontent.com/15819577/220075345-ed03197c-0532-4496-a0e5-5031e718bb41.png)

This is fine for a single layer. But Users may want to add multiple layers.

![image](https://user-images.githubusercontent.com/15819577/220075955-179c6893-3c7d-460a-8691-df35a886c4a2.png)

Currently, no other layers have a legend which is no good.

There are several options. We could do the PCT approach of multiple floating boxes

![image](https://user-images.githubusercontent.com/15819577/220078112-30687bdf-c6c7-4e0d-9258-45a81dd86b0d.png)

But this can get cluttered especially on smaller screens.

Or we could put multiple legends in the box in the bottom left.

But I've had two ideas:

The first is to move from vertical dots/boxes to a horizontal bar

![image](https://user-images.githubusercontent.com/15819577/220074568-e98c3cb1-9bb1-46c6-ae2a-631a7471c620.png)

I think this remains clear, but it is more compact. But is probably does limit the number of values we can have. Especially if they need text tables.

The second idea is to place the legends below checkboxes/dropdown menus. These can still be contextual and have the added benefit of being next to the control that enables them. I think this may give users a clear idea about which legends are related to which layers/options.

**Comment by mem48** [comment]
Mockup of  UI

![image](https://user-images.githubusercontent.com/15819577/220082269-5a957c40-d741-4c27-8c23-f113884aca44.png)

**Comment by mem48** [comment]
8 bars is probably about the most we can fit in

![image](https://user-images.githubusercontent.com/15819577/220083391-e308c85a-9f4c-472e-8128-c6d7ca79c78a.png)

**Comment by mem48** [comment]
@Robinlovelace would be good to get your thoughts on this

**Comment by Robinlovelace** [comment]
> Mockup of UI
> 
> ![image](https://user-images.githubusercontent.com/15819577/220082269-5a957c40-d741-4c27-8c23-f113884aca44.png)

I like this idea.

**Comment by Robinlovelace** [comment]
> The first is to move from vertical dots/boxes to a horizontal bar
> 
> ![image](https://user-images.githubusercontent.com/15819577/220074568-e98c3cb1-9bb1-46c6-ae2a-631a7471c620.png)

This is also a reasonable solution.

**Comment by Robinlovelace** [comment]
No strong preference. I suggest whichever will be simpler, quicker to implement, and easier to modify based on user feedback for the fast track layer. What you you reckon @mem48 ?

**Comment by mem48** [comment]
Ok I'll give it a go and see how it looks

**Comment by mem48** [comment]
I've implemented a test of this. I'm not quite happy with how it works when layers are off, but should give the basic idea.

@Robinlovelace can you give it a spin

**Comment by Robinlovelace** [comment]
Will take a look.

**Comment by Robinlovelace** [comment]
Looking really good.

**Comment by mem48** [comment]
No working for multiple layers

![image](https://user-images.githubusercontent.com/15819577/221201132-22485c01-fd6b-4173-99e6-7a508f35e983.png)

I'm not going to bother with zones. As that will be merged into data zones at a later date

**Comment by Robinlovelace** [comment]
Looking good.
