### ISSUE TITLE
Move basemap controls to bottom (less important)

### ISSUE THREAD

**Issue by mem48** [nptscot/web#23]

**Comment by Robinlovelace** [comment]
Looking at this now.

**Comment by Robinlovelace** [comment]
Going to crate a Development branch by clicking on the button...

**Comment by Robinlovelace** [comment]
Fixed I think.

Before:

![image](https://user-images.githubusercontent.com/1825120/224134163-27ab8d40-87de-4201-8a98-31da6d1b7428.png)


After:

![image](https://user-images.githubusercontent.com/1825120/224133416-7fa4029d-9fce-4049-80cc-9d8b3088ff8b.png)
