### ISSUE TITLE
Reorder admin boundaries

### ISSUE THREAD

**Issue by mem48** [nptscot/web#26]
Wards,
Scot Parliment
LA
Westminster

**Comment by Robinlovelace** [comment]
Taking a look at this now.

**Comment by Robinlovelace** [comment]
Before:

![image](https://user-images.githubusercontent.com/1825120/224112084-cb7fc1d3-da7d-420c-92a5-ddb74c25e99e.png)


After:

![image](https://user-images.githubusercontent.com/1825120/224111761-51cb78bb-2769-4b50-8ebb-cb58859c252d.png)
