### ISSUE TITLE
UI Wishlist

### ISSUE THREAD

**Issue by mem48** [nptscot/web#3]
- [x] Visualise quietness like in CRUSE
- [x] Visualise hilliness
- [x] Remove the ability to visualise other modes in routes: unrealistic as these are cycle routes not car/bus/other routes and also distracting
- [x] Add placeholder enabling people to switch network type, fastest, balanced, quietest
- [x] Zones
- [x] Popup on click
- [x] Info/Help popups
- [x] Sliders

**Comment by mem48** [comment]
- [ ] Zones
- [ ] Popup on click

**Comment by Robinlovelace** [comment]
> * [ ]  Zones
> 
>     * [ ]  Popup on click

Ported to top level :+1:
