### ISSUE TITLE
Add quietness styling

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/web#4]
Currently it's like this:

![image](https://user-images.githubusercontent.com/1825120/213427738-d70da2d9-20f4-4655-a9e2-215f9875ea43.png)

We want something more like CRUSE:

![image](https://user-images.githubusercontent.com/1825120/213427950-daa1155c-4959-4066-a261-860171c339f8.png)

**Comment by mem48** [comment]
Done and also gradient

![image](https://user-images.githubusercontent.com/15819577/213438752-47e0322c-0119-4ded-ac0a-c9d98aa22bdb.png)

![image](https://user-images.githubusercontent.com/15819577/213438768-8b2bd212-77d6-493d-865e-880c27741f09.png)

**Comment by Robinlovelace** [comment]
Looking good. Not sure about pinks for gradient but great work!

**Comment by mem48** [comment]
You now know how to change colours, remember to change the legend as well in the same file.

**Comment by Robinlovelace** [comment]
A good one to ask users/funders. Also, you're the JS guy @mem48 so more in your court. No action needed now, just asking the question.

**Comment by temospena** [comment]
Hi,

Congratulations on a great job - taking the PCT to another level! 🪁 

Sorry to jump in here like this, but still regarding the gradient style...

It intuitively seems to me that gradient color 0-3 and 3-5 should be reverse, as 0-3 dark green, and 3-5 a green closer to the next threshold (yellow).

![image](https://github.com/nptscot/nptscot.github.io/assets/39107166/62a0efcc-4157-49bc-bb1e-fc1627ad10dd)

exemple bellow. no?
![image](https://github.com/nptscot/nptscot.github.io/assets/39107166/8c3859f6-272c-409f-b814-1c5ebe3031a4)

**Comment by Robinlovelace** [comment]
Thanks for this @temospena. I agree, good point. May not be a priority, interested in what @mem48 thinks. We do have some high priority issues, may be worth opening a separate issue for this so we don't forget though.
